import pandas as pd

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error

In [9]:
df=pd.read_csv("BostonHousing (1).csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [11]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [35]:
x=df[['crim', 'zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]

In [37]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [39]:
y=df['medv']
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [45]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [47]:
y_pred=model.predict(x_test)
y_pred

array([ 0.87753975, 26.23394497, 18.30807696, 20.85583278, 19.3246992 ,
       31.1846138 , 24.62312403, 11.93975923, 25.17807385, 20.29028847,
       20.44981621, 24.87954331, 33.10081687, 33.34040143, 19.61633308,
       16.1097347 , 22.9408751 , 18.29341886, 12.88584909, 22.21905691,
       24.81589397, 40.64159502, 20.42076584, 20.68355222, 40.66884084,
       28.0707899 , 30.5986707 , 21.52460709, 27.43200143,  7.76516594,
       19.48878616, 32.22033225, 13.97068381, 28.53205296, 29.2981408 ,
       16.21778684, 22.304308  , 18.07829809, 17.83630434, 27.6653009 ,
       28.25615701, 36.10244035, 15.00689556, 19.73964948, 13.51284698,
       32.90337234, 27.49879722, 13.19061726, 35.46529242, 21.29805265,
       15.44385089, 13.54253096, 28.57509892, 23.66648326, 16.94713029,
       20.10848216, 23.41515653, 17.65019942, 24.20936365, 29.13800451,
       31.09051603, 21.91667902, 14.72999492, 31.2460839 , 27.4623661 ,
       21.63474768, 37.01068802,  9.59165918, 14.35071889, 21.30183502,
       18.99339148, 27.91936239, 24.75324672, 17.29387241, 19.90850618,
       19.7852069 , 17.29827099, 33.28208799, 32.99725133, 25.5536272 ,
       18.48443305, 23.64709445, 29.06591608, 31.78574834, 23.08206368,
       22.79675905, 35.28764015, 31.04214279, 31.62330286, 25.37134194,
       30.64741028, 26.32888848, 25.16220416,  3.70296729, 25.91944136,
       25.55571288, 33.40571018, 22.16048762, 23.63468994, 29.72552652,
       20.61387467, 17.98338747, 18.37184391,  6.92107895,  7.13232971,
       21.62493877, 36.26613856, 30.57859868, 23.2552843 , 41.31661815,
       23.71874378, 29.29859756, 18.75458202, 25.82077899, 18.7606309 ,
       14.34396887, 26.65593885, 34.41573738, 24.76566462, 19.50444476,
       24.02873673, 22.58516226, 20.38591535, 14.5353305 , 20.40258066,
       15.00081739, 36.63543605])

In [51]:
model.score(x_train,y_train)

0.7678970769610902

In [53]:
model.score(x_test,y_test)

0.6521788321823769

In [55]:
mean_squared_error(y_test,y_pred)

32.32937653333731

In [57]:
np.sqrt(mean_squared_error(y_test,y_pred))

5.685892764846811