In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Iris_dataset.csv")

In [5]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower_name
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [7]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [9]:
df['sepal length (cm)'].mean()

5.843333333333334

In [11]:
df['sepal length (cm)'].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal length (cm), dtype: float64

In [13]:
df.groupby('flower_name').describe()

            sepal length (cm)                                              \
                        count   mean       std  min    25%  50%  75%  max
flower_name
setosa                   50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor               50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica                50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

            sepal width (cm)         ... petal length (cm)       \
                       count   mean  ...               75%  max
flower_name                          ...
setosa                  50.0  3.428  ...             1.575  1.9
versicolor              50.0  2.770  ...             4.600  5.1
virginica               50.0  2.974  ...             5.875  6.9

            petal width (cm)
                       count   mean       std  min  25%  50%  75%  max
flower_name
setosa                  50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6
versicolor              50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
virginica               50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]